<?php
if (!defined('ABSPATH')) exit;

final class Zica_Posts_Outbox {
    private $auth; private $discovery; private static $suppress_outbound=false;
    public function __construct($auth,$discovery){$this->auth=$auth;$this->discovery=$discovery;add_action('transition_post_status',array($this,'on_transition'),20,3);add_action('post_updated',array($this,'on_updated'),20,3);add_action(ZICA_POSTS_CRON_OUTBOX,array($this,'process'));add_action(ZICA_POSTS_CRON_DAILY,array($this,'daily_reconcile'));}
    public static function suppress($value=null){if(null!==$value)self::$suppress_outbound=(bool)$value;return self::$suppress_outbound;}
    public function ensure_table(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$table=$wpdb->prefix.ZICA_POSTS_OUTBOX_TABLE;$charset=$wpdb->get_charset_collate();$sql="CREATE TABLE {$table} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,event_id char(36) NOT NULL,post_id bigint(20) unsigned NOT NULL DEFAULT 0,event_type varchar(40) NOT NULL,content_hash char(64) NOT NULL,correlation_id varchar(80) NOT NULL,status varchar(20) NOT NULL DEFAULT 'pending',attempts smallint unsigned NOT NULL DEFAULT 0,next_attempt_at datetime NULL,last_error text NULL,created_at datetime NOT NULL,delivered_at datetime NULL,PRIMARY KEY (id),UNIQUE KEY event_id (event_id),KEY status_next (status,next_attempt_at),KEY post_hash (post_id,content_hash)) {$charset};";dbDelta($sql);}
    private function next_daily_timestamp(){$tz=new DateTimeZone(ZICA_POSTS_TZ);$now=new DateTimeImmutable('now',$tz);$next=$now->setTime(15,0,0);if($next<=$now)$next=$next->modify('+1 day');return $next->getTimestamp();}
    public function clear_schedules(){foreach(array(ZICA_POSTS_CRON_DAILY,ZICA_POSTS_CRON_OUTBOX,ZICA_POSTS_CRON_DISCOVERY) as $hook){$ts=wp_next_scheduled($hook);while($ts){wp_unschedule_event($ts,$hook);$ts=wp_next_scheduled($hook);}}}
    public function ensure_schedules(){if(!wp_next_scheduled(ZICA_POSTS_CRON_DAILY))wp_schedule_single_event($this->next_daily_timestamp(),ZICA_POSTS_CRON_DAILY);if(!wp_next_scheduled(ZICA_POSTS_CRON_OUTBOX))wp_schedule_event(time()+60,'five_minutes',ZICA_POSTS_CRON_OUTBOX);}
    public function content_hash($post){if(!$post instanceof WP_Post)return hash('sha256','missing');return hash('sha256',wp_json_encode(array('id'=>$post->ID,'status'=>$post->post_status,'title'=>$post->post_title,'content'=>$post->post_content,'excerpt'=>$post->post_excerpt,'slug'=>$post->post_name,'modified'=>$post->post_modified_gmt),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));}
    public function enqueue($post_id,$event_type,$correlation_id=''){if(self::$suppress_outbound)return false;$post=get_post(absint($post_id));if(!$post instanceof WP_Post||!in_array($post->post_type,array('post','page'),true))return false;global $wpdb;$table=$wpdb->prefix.ZICA_POSTS_OUTBOX_TABLE;$hash=$this->content_hash($post);$existing=$wpdb->get_var($wpdb->prepare("SELECT event_id FROM {$table} WHERE post_id=%d AND content_hash=%s AND status IN ('pending','processing','delivered') ORDER BY id DESC LIMIT 1",$post->ID,$hash));if($existing)return $existing;$event_id=wp_generate_uuid4();$correlation_id=$correlation_id?sanitize_text_field($correlation_id):wp_generate_uuid4();$wpdb->insert($table,array('event_id'=>$event_id,'post_id'=>$post->ID,'event_type'=>sanitize_key($event_type),'content_hash'=>$hash,'correlation_id'=>$correlation_id,'status'=>'pending','attempts'=>0,'created_at'=>current_time('mysql',true),'next_attempt_at'=>current_time('mysql',true)),array('%s','%d','%s','%s','%s','%s','%d','%s','%s'));return $event_id;}
    public function on_transition($new,$old,$post){if(self::$suppress_outbound||!$post instanceof WP_Post||'publish'!==$new||'publish'===$old)return;if(wp_is_post_revision($post->ID)||wp_is_post_autosave($post->ID))return;$this->enqueue($post->ID,'published');}
    public function on_updated($post_id,$after,$before){if(self::$suppress_outbound||!$after instanceof WP_Post||'publish'!==$after->post_status)return;if(!in_array($after->post_type,array('post','page'),true))return;if($this->content_hash($after)===$this->content_hash($before))return;$this->enqueue($post_id,'updated');}
    private function payload($row){$post=get_post((int)$row->post_id);if(!$post instanceof WP_Post)return null;return array('event_id'=>$row->event_id,'event_type'=>$row->event_type,'content_hash'=>$row->content_hash,'correlation_id'=>$row->correlation_id,'site'=>home_url('/'),'fetch_url'=>rest_url('zica-posts/v1/articles/'.$post->ID),'post'=>array('id'=>$post->ID,'type'=>$post->post_type,'status'=>$post->post_status,'title'=>$post->post_title,'slug'=>$post->post_name,'url'=>get_permalink($post->ID),'modified_gmt'=>$post->post_modified_gmt),'software'=>array('id'=>ZICA_POSTS_SOFTWARE_ID,'version'=>ZICA_POSTS_VERSION));}
    private function dispatch_hub($events){$url=esc_url_raw((string)get_option('zica_posts_hub_webhook_url',''));if('1'!==(string)get_option('zica_posts_hub_enabled','0')||!$url)return array('skipped'=>true,'reason'=>'hub_disabled');if(!$this->auth->hub_url_is_safe($url))return array('ok'=>false,'error'=>'unsafe_hub_url');$body=wp_json_encode(array('site'=>home_url('/'),'events'=>array_values($events)),JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$timestamp=(string)time();$nonce=wp_generate_uuid4();$response=wp_remote_post($url,array('timeout'=>8,'redirection'=>0,'headers'=>array('Content-Type'=>'application/json','X-Zica-Software-ID'=>ZICA_POSTS_SOFTWARE_ID,'X-Zica-Timestamp'=>$timestamp,'X-Zica-Nonce'=>$nonce,'X-Zica-Signature'=>$this->auth->sign_body($body,$nonce,$timestamp)),'body'=>$body));if(is_wp_error($response))return array('ok'=>false,'error'=>$response->get_error_message());$code=wp_remote_retrieve_response_code($response);return array('ok'=>$code>=200&&$code<300,'http'=>$code);}
    public function process(){if(get_transient('zica_posts_outbox_lock'))return array('skipped'=>true,'reason'=>'locked');set_transient('zica_posts_outbox_lock','1',240);global $wpdb;$table=$wpdb->prefix.ZICA_POSTS_OUTBOX_TABLE;$now=current_time('mysql',true);$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$table} WHERE status IN ('pending','retry') AND (next_attempt_at IS NULL OR next_attempt_at<=%s) ORDER BY id ASC LIMIT 100",$now));$events=array();$row_ids=array();$urls=array();foreach((array)$rows as $row){$payload=$this->payload($row);if(!$payload){$wpdb->update($table,array('status'=>'discarded','last_error'=>'post_not_found'),array('id'=>$row->id));continue;}$events[]=$payload;$row_ids[]=(int)$row->id;if(!empty($payload['post']['url']))$urls[]=$payload['post']['url'];$wpdb->update($table,array('status'=>'processing','attempts'=>(int)$row->attempts+1),array('id'=>$row->id));}$hub_enabled='1'===(string)get_option('zica_posts_hub_enabled','0')&&(bool)get_option('zica_posts_hub_webhook_url','');$delegate_indexing=$hub_enabled&&'1'===(string)get_option('zica_posts_hub_delegates_indexing','1');$delegate_discovery=$hub_enabled&&'1'===(string)get_option('zica_posts_hub_delegates_discovery','0');$files=$delegate_discovery?array('delegated'=>true):$this->discovery->refresh_files();$indexnow=$delegate_indexing?array('delegated'=>true,'requested'=>count($urls),'provider'=>'Zica Orchestrator'):$this->discovery->submit_indexnow_batch($urls,500);$hub=$events?$this->dispatch_hub($events):array('skipped'=>true,'reason'=>'empty');$hub_ok=!empty($hub['ok'])||!empty($hub['skipped']);foreach($row_ids as $id){if($hub_ok)$wpdb->update($table,array('status'=>'delivered','delivered_at'=>$now,'last_error'=>null),array('id'=>$id));else{$attempts=(int)$wpdb->get_var($wpdb->prepare("SELECT attempts FROM {$table} WHERE id=%d",$id));$minutes=min(60,max(2,(int)pow(2,min(5,$attempts))));$next=gmdate('Y-m-d H:i:s',time()+$minutes*60);$wpdb->update($table,array('status'=>$attempts>=5?'failed':'retry','next_attempt_at'=>$next,'last_error'=>sanitize_text_field(isset($hub['error'])?$hub['error']:'hub_http_'.(isset($hub['http'])?$hub['http']:'unknown'))),array('id'=>$id));}}$result=array('mode'=>'outbox','at'=>$now,'events'=>count($events),'files'=>$files,'indexnow'=>$indexnow,'hub'=>$hub);update_option('zica_posts_last_sync',$result,false);delete_transient('zica_posts_outbox_lock');return $result;}
    public function daily_reconcile(){if(get_transient('zica_posts_daily_lock')){$this->ensure_schedules();return;}set_transient('zica_posts_daily_lock','1',300);$ids=get_posts(array('post_type'=>array('post','page'),'post_status'=>'publish','posts_per_page'=>1500,'orderby'=>'modified','order'=>'DESC','date_query'=>array(array('column'=>'post_modified_gmt','after'=>'2 days ago')),'fields'=>'ids'));foreach($ids as $id)$this->enqueue($id,'daily_reconcile');$this->process();delete_transient('zica_posts_daily_lock');if(!wp_next_scheduled(ZICA_POSTS_CRON_DAILY))wp_schedule_single_event($this->next_daily_timestamp(),ZICA_POSTS_CRON_DAILY);}
    public function counts(){global $wpdb;$table=$wpdb->prefix.ZICA_POSTS_OUTBOX_TABLE;$rows=$wpdb->get_results("SELECT status,COUNT(*) total FROM {$table} GROUP BY status",ARRAY_A);$out=array();foreach((array)$rows as $row)$out[$row['status']]=(int)$row['total'];return $out;}
    public function recent($limit=50){global $wpdb;$table=$wpdb->prefix.ZICA_POSTS_OUTBOX_TABLE;$limit=min(100,max(1,absint($limit)));return $wpdb->get_results("SELECT event_id,post_id,event_type,content_hash,correlation_id,status,attempts,last_error,created_at,delivered_at FROM {$table} ORDER BY id DESC LIMIT {$limit}",ARRAY_A);}
}
