import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { fetchEffectiveAIKeys } from "../_shared/byok-resolver.ts";
import { adminClient, errorStatus, getRuntimeKeys, resolveUserCaller } from "../_shared/supabase-runtime.ts";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const OPENAI_IMAGE_MODEL="gpt-image-2";
const CLAUDE_MODEL="claude-sonnet-4-6";
const VISUAL_TEMPLATE="visual_content_master_v1";
type OutputFormat="square"|"landscape"|"portrait";
type Input={campaignPresetId:string;projectId?:string|null;referenceAssetIds?:string[];prompt?:string;primaryOverlay?:string;secondaryOverlay?:string;politicalParty?:string;ballotName?:string;ballotNumber?:string;outputFormat?:OutputFormat};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json","Cache-Control":"no-store"}});
function unb64(value:string){const raw=atob(value),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function extension(mime:string){if(mime==="image/png")return"png";if(mime==="image/webp")return"webp";return"jpg";}
function sizeFor(format:OutputFormat){if(format==="portrait")return"1024x1536";if(format==="landscape")return"1536x1024";return"1024x1024";}

async function reviewPromptWithClaude(apiKey:string,prompt:string){if(!apiKey)return{prompt,reviewed:false};try{const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"x-api-key":apiKey,"anthropic-version":"2023-06-01","Content-Type":"application/json"},body:JSON.stringify({model:CLAUDE_MODEL,max_tokens:1800,messages:[{role:"user",content:`Revise o prompt eleitoral abaixo sem mudar a identidade da pessoa da ÚNICA foto de referência. A referência é fonte de identidade, não inspiração genérica. Preserve rosto, cabelo, barba, idade aparente, tom de pele, proporções e características individuais; não misture nem crie outra face. Não invente terceiro, evento, documento, uniforme, apoio ou endosso. Retorne somente o prompt final.\n\n${prompt}`}]}),signal:AbortSignal.timeout(45000)});if(!res.ok)return{prompt,reviewed:false};const data=await res.json(),reviewed=Array.isArray(data?.content)?data.content.map((part:{text?:string})=>part.text||"").join("\n").trim():"";return{prompt:reviewed||prompt,reviewed:Boolean(reviewed)};}catch{return{prompt,reviewed:false};}}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{headers:corsHeaders});if(req.method!=="POST")return json({success:false,error:"method_not_allowed"},405);const requestId=crypto.randomUUID();let jobId="";try{const input=await req.json() as Input,presetId=String(input.campaignPresetId||"").trim();if(!presetId)return json({success:false,error:"campaign_preset_required",request_id:requestId},422);const runtime=getRuntimeKeys();if(!runtime.url||!runtime.publicKey||!runtime.secretKey)return json({success:false,error:"backend_not_configured",request_id:requestId},500);const caller=await resolveUserCaller(req,runtime,null);if(caller.internal)return json({success:false,error:"user_session_required",request_id:requestId},401);const userId=caller.userId,admin=adminClient(runtime);
const[{data:template},keys]=await Promise.all([admin.from("prompt_templates").select("prompt,agent_name").eq("user_id",userId).eq("name",VISUAL_TEMPLATE).maybeSingle(),fetchEffectiveAIKeys(userId)]);if(!keys.openai)return json({success:false,error:"OpenAI não configurada para este usuário.",code:"openai_missing",request_id:requestId},503);

const requestedIds=Array.isArray(input.referenceAssetIds)?input.referenceAssetIds.filter(Boolean):[];if(requestedIds.length>1)return json({success:false,error:"Selecione exatamente uma foto de referência por geração.",code:"single_reference_required",request_id:requestId},422);
let reference:any=null;
if(requestedIds.length===1){const{data,error}=await admin.from("electoral_visual_assets").select("id,storage_path,mime_type,status,is_default,alt_text").eq("id",requestedIds[0]).eq("user_id",userId).eq("campaign_preset_id",presetId).eq("asset_kind","reference").in("status",["ready","approved"]).maybeSingle();if(error)throw error;reference=data;}else{const{data}=await admin.from("electoral_visual_assets").select("id,storage_path,mime_type,status,is_default,alt_text").eq("user_id",userId).eq("campaign_preset_id",presetId).eq("asset_kind","reference").in("status",["ready","approved"]).order("is_default",{ascending:false}).order("created_at",{ascending:true}).limit(1).maybeSingle();reference=data;}
if(!reference)return json({success:false,error:"Selecione uma foto de referência válida antes de gerar.",code:"reference_required",request_id:requestId},422);

const format:OutputFormat=input.outputFormat==="portrait"||input.outputFormat==="landscape"?input.outputFormat:"square",primary=String(input.primaryOverlay||`DR. MADEIRA ${input.ballotNumber||"1470"}`).trim(),secondary=String(input.secondaryOverlay||`FEDERAL ${input.ballotNumber||"1470"}`).trim(),operatorPrompt=String(input.prompt||"Criar peça eleitoral premium preservando a pessoa da foto selecionada.").trim().slice(0,5000),master=String(template?.prompt||"").trim();
const basePrompt=`${master}\n\nMODO: ELEITORAL / EDIÇÃO COM REFERÊNCIA ÚNICA ESTRITA.\nCandidato: ${input.ballotName||"Dr. Madeira"}. Número: ${input.ballotNumber||"1470"}. Partido: ${input.politicalParty||"Partido MISSÃO"}.\nPedido do operador: ${operatorPrompt}\nBranding solicitado: "${primary}" e "${secondary}".\n\nA IMAGEM ANEXADA É A FONTE ÚNICA DE IDENTIDADE.\n- Preserve a mesma pessoa da foto anexada. Não sintetize uma identidade alternativa e não misture traços de outras pessoas.\n- Mantenha rosto, cabelo, barba, idade aparente, tom de pele e proporções reconhecíveis da referência.\n- Faça alterações de fundo, enquadramento, iluminação, roupa genérica não identificadora e composição somente na medida necessária à peça solicitada.\n- Não fazer face-swap, não criar sósia, não inventar terceiro ou apoio público.\n- Não representar fato jornalístico, comício, reunião, autoridade, uniforme ou documento como ocorrido sem referência factual.\n- Evitar pele plástica, anatomia incorreta, mãos deformadas e estética de banco de imagens.\n- Composição ${format}; safe-zone; contraste alto e leitura mobile.\n- Quando o modelo renderizar texto, tentar manter exatamente: ${primary} / ${secondary}.\n- A saída é mídia sintética derivada da referência e exige aprovação humana.`;
const reviewed=await reviewPromptWithClaude(keys.anthropic,basePrompt);
const{data:job,error:jobError}=await admin.from("electoral_image_jobs").insert({user_id:userId,project_id:input.projectId||null,campaign_preset_id:presetId,status:"running",provider:"openai",generation_mode:"strict-single-reference-edit-gpt-image-2",fidelity_preference:1,reference_asset_ids:[reference.id],requested_formats:{selected:format,model_size:sizeFor(format)},overlay_config:{primary,secondary,safeZone:true,party:input.politicalParty||null},prompt_context:reviewed.prompt}).select("id").single();if(jobError||!job)throw jobError||new Error("job_create_failed");jobId=job.id;

const{data:blob,error:downloadError}=await admin.storage.from("electoral-assets").download(reference.storage_path);if(downloadError||!blob)throw downloadError||new Error("reference_download_failed");const bytes=new Uint8Array(await blob.arrayBuffer()),mime=reference.mime_type||blob.type||"image/jpeg",form=new FormData();form.set("model",OPENAI_IMAGE_MODEL);form.set("prompt",reviewed.prompt);form.set("size",sizeFor(format));form.set("quality","high");form.append("image[]",new File([bytes],`reference.${extension(mime)}`,{type:mime}));
const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),150000);let openaiResponse:Response;try{openaiResponse=await fetch("https://api.openai.com/v1/images/edits",{method:"POST",headers:{Authorization:`Bearer ${keys.openai}`},body:form,signal:controller.signal});}finally{clearTimeout(timeout);}
const providerPayload=await openaiResponse.json().catch(()=>({}));if(!openaiResponse.ok){const code=String(providerPayload?.error?.code||"openai_image_error"),message=String(providerPayload?.error?.message||`OpenAI HTTP ${openaiResponse.status}`),credit=code==="credit_balance_exhausted"||code==="insufficient_quota"||/no credits|credit balance|quota/i.test(message);await admin.from("electoral_image_jobs").update({status:credit?"provider_unavailable":"failed",error_message:`${code}: ${message}`.slice(0,1000),completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",jobId).eq("user_id",userId);return json({success:false,error:credit?"A OpenAI está conectada, mas a conta está sem créditos para gerar a imagem.":message,code:credit?"openai_credit_balance_exhausted":code,retryable:!credit,request_id:requestId},credit?402:openaiResponse.status);}
const first=providerPayload?.data?.[0];let outputBytes:Uint8Array,outputMime="image/png";if(first?.b64_json)outputBytes=unb64(String(first.b64_json));else if(first?.url){const imageResponse=await fetch(String(first.url),{signal:AbortSignal.timeout(60000)});if(!imageResponse.ok)throw new Error(`generated_image_download_http_${imageResponse.status}`);outputMime=imageResponse.headers.get("content-type")||"image/png";outputBytes=new Uint8Array(await imageResponse.arrayBuffer());}else throw new Error("gpt_image_2_missing_output");
const path=`${userId}/${presetId}/generated/${crypto.randomUUID()}.png`;const{error:uploadError}=await admin.storage.from("electoral-assets").upload(path,outputBytes,{contentType:outputMime,upsert:false,cacheControl:"31536000"});if(uploadError)throw uploadError;const[width,height]=sizeFor(format).split("x").map(Number),{data:asset,error:assetError}=await admin.from("electoral_visual_assets").insert({user_id:userId,project_id:input.projectId||null,campaign_preset_id:presetId,asset_kind:"generated",status:"ready",storage_path:path,source_asset_id:reference.id,width,height,mime_type:outputMime,file_size_bytes:outputBytes.byteLength,alt_text:`Imagem sintética eleitoral derivada da foto selecionada de ${input.ballotName||"Dr. Madeira"} ${input.ballotNumber||"1470"}`,overlay_config:{primary,secondary,safeZone:true},metadata:{source:"nexus-visual-studio",prompt_template:VISUAL_TEMPLATE,prompt_reviewed_by_claude:reviewed.reviewed,reviewer_model:reviewed.reviewed?CLAUDE_MODEL:null,provider:"openai",model:OPENAI_IMAGE_MODEL,key_source:keys.sources.openai,synthetic_media:true,synthetic_media_disclosure_required:true,reference_policy:"strict_single_source",source_reference_asset_id:reference.id,output_format:format}}).select("id,storage_path,status,width,height,alt_text,source_asset_id,created_at").single();if(assetError||!asset)throw assetError||new Error("asset_insert_failed");await admin.from("electoral_image_jobs").update({status:"completed",output_asset_ids:[asset.id],provider_job_id:String(providerPayload?.id||""),error_message:null,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",jobId).eq("user_id",userId);const{data:signed}=await admin.storage.from("electoral-assets").createSignedUrl(path,3600);return json({success:true,request_id:requestId,job_id:jobId,asset:{...asset,signedUrl:signed?.signedUrl||null},provider:"openai",model:OPENAI_IMAGE_MODEL,promptReviewedByClaude:reviewed.reviewed,reviewerModel:reviewed.reviewed?CLAUDE_MODEL:null,referencePolicy:"strict_single_source",sourceReferenceAssetId:reference.id,syntheticMedia:true});
}catch(error){if(jobId){try{const runtime=getRuntimeKeys(),admin=adminClient(runtime);await admin.from("electoral_image_jobs").update({status:"failed",error_message:(error instanceof Error?error.message:"generation_failed").slice(0,1000),completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",jobId);}catch{}}return json({success:false,error:error instanceof Error?error.message:"generation_failed",request_id:requestId},errorStatus(error,500));}});
