import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { fetchEffectiveAIKeys } from "../_shared/byok-resolver.ts";
import { adminClient, getRuntimeKeys } from "../_shared/supabase-runtime.ts";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-zica-automation-key","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json","Cache-Control":"no-store"}});
async function sha256(value:string){const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function bucket(minutes:number){const ms=minutes*60000;return new Date(Math.floor(Date.now()/ms)*ms).toISOString();}
function clamp(value:number){return Math.max(0,Math.min(100,Math.round(value)));}
function stripHtml(value:string){return value.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim();}
function countMatches(value:string,re:RegExp){return(value.match(re)||[]).length;}
async function state(admin:any,userId:string,subsystem:string,status:"healthy"|"degraded"|"offline"|"unknown",metrics:Record<string,unknown>={},error?:string){const now=new Date().toISOString(),patch:any={user_id:userId,subsystem,status,last_heartbeat_at:now,last_error:error?error.slice(0,2000):null,metrics,updated_at:now};if(status==="healthy")patch.last_success_at=now;if(error)patch.last_error_at=now;await admin.from("zica_brain_state").upsert(patch,{onConflict:"user_id,subsystem"});}
async function enqueue(admin:any,row:Record<string,unknown>){const{error}=await admin.from("zica_brain_jobs").upsert(row,{onConflict:"user_id,idempotency_key",ignoreDuplicates:true});if(error&&!String(error.message).includes("duplicate"))throw error;}
async function edgeCall(baseUrl:string,secretKey:string,slug:string,body:Record<string,unknown>,timeoutMs=90000){const response=await fetch(`${baseUrl}/functions/v1/${slug}`,{method:"POST",headers:{apikey:secretKey,"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(timeoutMs)});const text=await response.text();let data:any=null;try{data=JSON.parse(text)}catch{data={error:text.slice(0,800)}}return{ok:response.ok&&data?.success!==false,status:response.status,data};}

async function providerHealth(admin:any,userId:string){const keys=await fetchEffectiveAIKeys(userId),checkedAt=new Date().toISOString(),result:any={checked_at:checkedAt,key_sources:keys.sources};
if(keys.openai){try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${keys.openai}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-sol",input:"Responda somente OK.",max_output_tokens:16,store:false}),signal:AbortSignal.timeout(30000)});const text=await r.text();let payload:any={};try{payload=JSON.parse(text)}catch{}result.openai={configured:true,operational:r.ok,httpStatus:r.status,model:"gpt-5.6-sol",errorCode:payload?.error?.code||null,errorType:payload?.error?.type||null,keySource:keys.sources.openai};}catch(e){result.openai={configured:true,operational:false,httpStatus:0,model:"gpt-5.6-sol",errorCode:"network_error",keySource:keys.sources.openai,detail:e instanceof Error?e.message:"error"};}}else result.openai={configured:false,operational:false,httpStatus:null,keySource:"missing"};
if(keys.anthropic){try{const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"x-api-key":keys.anthropic,"anthropic-version":"2023-06-01","Content-Type":"application/json"},body:JSON.stringify({model:"claude-sonnet-4-6",max_tokens:8,messages:[{role:"user",content:"Responda somente OK."}]}),signal:AbortSignal.timeout(30000)});const payload=await r.json().catch(()=>({}));result.anthropic={configured:true,operational:r.ok,httpStatus:r.status,model:"claude-sonnet-4-6",errorType:payload?.error?.type||null,keySource:keys.sources.anthropic};}catch(e){result.anthropic={configured:true,operational:false,httpStatus:0,model:"claude-sonnet-4-6",errorType:"network_error",keySource:keys.sources.anthropic,detail:e instanceof Error?e.message:"error"};}}else result.anthropic={configured:false,operational:false,httpStatus:null,keySource:"missing"};
for(const provider of["openai","anthropic"]as const)await admin.from("zica_ai_provider_health_cache").upsert({provider,checked_at:checkedAt,payload:{provider:result[provider],operational:result[provider]?.operational===true,billable_probe:true,key_source:keys.sources[provider]}},{onConflict:"provider"});return result;}

async function auditArticle(admin:any,userId:string,articleId:string){const{data:article}=await admin.from("articles").select("id,title,content,excerpt,keyword,secondary_keywords,originality_score,status,project_id,published_url,config").eq("id",articleId).eq("user_id",userId).maybeSingle();if(!article)throw new Error("article_not_found");const html=String(article.content||""),text=stripHtml(html),words=text.split(/\s+/).filter(Boolean),h2=countMatches(html,/<h2\b/gi)+countMatches(html,/^##\s+/gm),h3=countMatches(html,/<h3\b/gi)+countMatches(html,/^###\s+/gm),links=countMatches(html,/href=["'][^"']+["']/gi)+countMatches(html,/https?:\/\/[^\s<)]+/gi),internalSuggestions=Array.isArray(article.config?.internal_link_suggestions)?article.config.internal_link_suggestions.length:0,sourceCount=[article.config?.primary_sources,article.config?.secondary_sources,article.config?.legal_authorities].filter(Array.isArray).reduce((sum:number,arr:any)=>sum+arr.length,0),faq=/FAQ|perguntas frequentes|<details|FAQPage/i.test(html),hasExcerpt=String(article.excerpt||"").trim().length>=80,hasKeyword=String(article.keyword||"").trim().length>2,hasTitle=String(article.title||"").trim().length>10;let discovery=0;if(article.project_id){const{data:stats}=await admin.from("wordpress_stats").select("raw_data,total_internal_links").eq("project_id",article.project_id).maybeSingle();const serialized=JSON.stringify(stats?.raw_data||{});if(/llms\.txt/i.test(serialized))discovery+=5;if(/ai\.txt/i.test(serialized))discovery+=4;if(/sitemap/i.test(serialized))discovery+=4;if(/schema/i.test(serialized))discovery+=4;}const llmReadiness=clamp(Math.min(30,words.length/60)+Math.min(20,(h2+h3)*3)+(faq?10:0)+Math.min(15,sourceCount*3)+Math.min(10,(links+internalSuggestions)*1.5)+(hasExcerpt?5:0)+(hasKeyword?5:0)+(hasTitle?5:0)+discovery),semanticAuthority=clamp(Math.min(30,words.length/70)+Math.min(15,(h2+h3)*2.5)+Math.min(15,sourceCount*3)+Math.min(15,links*2)+Math.min(10,internalSuggestions*2)+Math.min(10,Number(article.originality_score||0)/10)+(faq?5:0)),now=new Date().toISOString(),patch:any={llm_visibility_score:llmReadiness,semantic_authority_score:semanticAuthority,last_llm_audit_at:now,updated_at:now};if(article.status==="published")patch.traffic_wave_status="active";if(article.status==="error")patch.traffic_wave_status="error";await admin.from("articles").update(patch).eq("id",article.id).eq("user_id",userId);return{llm_readiness_score:llmReadiness,semantic_authority_score:semanticAuthority,metric_definition:"discoverability_readiness_not_observed_llm_citation",words:words.length,headings:h2+h3,sources:sourceCount,links};}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{headers:corsHeaders});if(req.method!=="POST")return json({success:false,error:"method_not_allowed"},405);const requestId=crypto.randomUUID(),started=Date.now();try{const runtime=getRuntimeKeys();if(!runtime.url||!runtime.secretKey)return json({success:false,error:"backend_not_configured",request_id:requestId},500);const admin=adminClient(runtime),automationKey=req.headers.get("x-zica-automation-key")||"",{data:ingress}=await admin.from("automation_ingress_keys").select("secret_hash,enabled").eq("name","zica-brain").maybeSingle();if(!automationKey||!ingress?.enabled||!ingress.secret_hash||await sha256(automationKey)!==ingress.secret_hash)return json({success:false,error:"automation_unauthorized",request_id:requestId},401);const body=await req.json().catch(()=>({})),maxJobs=Math.max(1,Math.min(50,Number(body?.maxJobs||20))),[{data:projectUsers},{data:articleUsers},{data:agentUsers}]=await Promise.all([admin.from("projects").select("user_id"),admin.from("articles").select("user_id"),admin.from("news_agents").select("user_id")]),users=[...new Set([...(projectUsers||[]),...(articleUsers||[]),...(agentUsers||[])].map((r:any)=>String(r.user_id)).filter(Boolean))],five=bucket(5),fifteen=bucket(15),sixHours=bucket(360);let enqueued=0;
for(const userId of users){await state(admin,userId,"brain","healthy",{phase:"enqueue",tick:requestId});const{data:projects}=await admin.from("projects").select("id").eq("user_id",userId).eq("is_connected",true).eq("wordpress_connector_mode","zica_posts");for(const project of projects||[]){await enqueue(admin,{user_id:userId,project_id:project.id,job_type:"wordpress_reconcile",status:"queued",priority:75,idempotency_key:`wordpress:${project.id}:${five}`,payload:{projectId:project.id},next_attempt_at:new Date().toISOString()});enqueued++;}
const{data:due}=await admin.from("articles").select("id,project_id,scheduled_at").eq("user_id",userId).eq("status","ready").not("scheduled_at","is",null).lte("scheduled_at",new Date().toISOString()).not("project_id","is",null).limit(100);for(const article of due||[]){await enqueue(admin,{user_id:userId,project_id:article.project_id,article_id:article.id,job_type:"scheduled_publish",status:"queued",priority:100,idempotency_key:`scheduled-publish:${article.id}:${article.scheduled_at}`,payload:{articleId:article.id,projectId:article.project_id},next_attempt_at:new Date().toISOString()});enqueued++;}
await enqueue(admin,{user_id:userId,job_type:"provider_health",status:"queued",priority:80,idempotency_key:`providers:${fifteen}`,payload:{},next_attempt_at:new Date().toISOString()});enqueued++;const cutoff=new Date(Date.now()-6*3600000).toISOString(),{data:auditRows}=await admin.from("articles").select("id").eq("user_id",userId).in("status",["ready","published"]).or(`last_llm_audit_at.is.null,last_llm_audit_at.lt.${cutoff}`).limit(50);for(const article of auditRows||[]){await enqueue(admin,{user_id:userId,article_id:article.id,job_type:"llm_audit",status:"queued",priority:55,idempotency_key:`llm-audit:${article.id}:${sixHours}`,payload:{articleId:article.id},next_attempt_at:new Date().toISOString()});enqueued++;}}
const{data:jobs,error:claimError}=await admin.rpc("claim_zica_brain_jobs",{p_limit:maxJobs,p_worker:`edge:${requestId}`});if(claimError)throw claimError;const results:any[]=[];for(const job of jobs||[]){let ok=false,result:any={},errorMessage="";try{if(job.job_type==="wordpress_reconcile"){const call=await edgeCall(runtime.url,runtime.secretKey,"wordpress-operations",{userId:job.user_id,projectId:job.project_id,action:"reconcile"},90000);ok=call.ok;result=call.data;errorMessage=call.ok?"":String(call.data?.error||`HTTP ${call.status}`);await state(admin,job.user_id,"wordpress",ok?"healthy":"degraded",{projectId:job.project_id,httpStatus:call.status},errorMessage||undefined);}else if(job.job_type==="scheduled_publish"){const call=await edgeCall(runtime.url,runtime.secretKey,"publish-to-wordpress",{userId:job.user_id,articleId:job.article_id,projectId:job.project_id,publishStatus:"publish",requireFeaturedImage:false},90000);ok=call.ok;result=call.data;errorMessage=call.ok?"":String(call.data?.error||`HTTP ${call.status}`);await state(admin,job.user_id,"scheduler",ok?"healthy":"degraded",{articleId:job.article_id,httpStatus:call.status},errorMessage||undefined);}else if(job.job_type==="provider_health"){result=await providerHealth(admin,job.user_id);const open=result.openai?.operational===true,claude=result.anthropic?.operational===true;ok=open||claude;await state(admin,job.user_id,"ai_providers",open&&claude?"healthy":ok?"degraded":"offline",{openai:result.openai,anthropic:result.anthropic},ok?undefined:"Nenhum provedor textual operacional");}else if(job.job_type==="llm_audit"||job.job_type==="semantic_audit"){result=await auditArticle(admin,job.user_id,job.article_id);ok=true;await state(admin,job.user_id,"semantic_metrics","healthy",{lastArticleId:job.article_id,...result});}else{ok=true;result={skipped:true,reason:"job_type_reserved"};}}catch(e){errorMessage=e instanceof Error?e.message:"job_failed";}await admin.rpc("finish_zica_brain_job",{p_id:job.id,p_ok:ok,p_result:result||{},p_error:errorMessage||null});results.push({id:job.id,type:job.job_type,ok,error:errorMessage||null});}
for(const userId of users){const dead=(await admin.from("zica_brain_jobs").select("id",{count:"exact",head:true}).eq("user_id",userId).eq("status","dead_letter")).count||0,retry=(await admin.from("zica_brain_jobs").select("id",{count:"exact",head:true}).eq("user_id",userId).eq("status","retry")).count||0;await state(admin,userId,"brain",dead>0?"degraded":"healthy",{requestId,enqueued,claimed:(jobs||[]).length,deadLetter:dead,retry,durationMs:Date.now()-started},dead>0?`${dead} job(s) em dead letter`:undefined);}return json({success:true,request_id:requestId,users:users.length,enqueued,claimed:(jobs||[]).length,results,duration_ms:Date.now()-started});}catch(error){return json({success:false,error:error instanceof Error?error.message:"brain_tick_failed",request_id:requestId,duration_ms:Date.now()-started},500);}});
