import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
type RSSItem={title:string;link:string;description:string;publishedAt:string|null;content?:string};
type Schedule={id:string;user_id:string;project_id:string|null;feed_url:string;feed_name:string;niche:string|null;article_length:string|null;frequency:string|null;auto_publish:boolean|null;last_run_at:string|null;next_run_at:string|null;articles_generated:number|null};
const J=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...H,"Content-Type":"application/json","Cache-Control":"no-store"}});
function jwtRole(token:string){try{const p=token.split('.')[1],n=p.replace(/-/g,'+').replace(/_/g,'/'),d=JSON.parse(atob(n.padEnd(Math.ceil(n.length/4)*4,'=')));return String(d?.role||'')}catch{return''}}
function decodeXml(v:string){return v.replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#039;/g,"'").trim()}
const strip=(v:string)=>decodeXml(v).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
function firstTag(xml:string,tag:string){const e=tag.replace(':','\\:');const m=xml.match(new RegExp(`<${e}[^>]*>([\\s\\S]*?)<\\/${e}>`,'i'));return m?.[1]?decodeXml(m[1]):''}
async function fetchFeed(url:string):Promise<RSSItem[]>{const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))throw new Error('RSS URL inválida');const r=await fetch(url,{headers:{'User-Agent':'Zica.ai-RSS/3.10.2',Accept:'application/rss+xml, application/atom+xml, application/xml, text/xml'},signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`RSS HTTP ${r.status}`);const xml=await r.text();if(xml.length>5_000_000)throw new Error('RSS excede 5 MB');const rss=[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)],atom=[...xml.matchAll(/<entry\b[^>]*>([\s\S]*?)<\/entry>/gi)],blocks=rss.length?rss.map(m=>m[1]):atom.map(m=>m[1]),items:RSSItem[]=[];for(const block of blocks.slice(0,20)){const title=strip(firstTag(block,'title'));let link=firstTag(block,'link');if(!link)link=block.match(/<link\b[^>]*href=["']([^"']+)["'][^>]*>/i)?.[1]||'';const desc=firstTag(block,'description')||firstTag(block,'summary'),content=firstTag(block,'content:encoded')||firstTag(block,'content'),date=firstTag(block,'pubDate')||firstTag(block,'published')||firstTag(block,'updated');if(!title||!link)continue;try{new URL(link)}catch{continue}items.push({title,link,description:strip(desc),content:content?strip(content):undefined,publishedAt:date?new Date(date).toISOString():null})}return items}
function nextRun(f:string|null){const n=(f||'daily').toLowerCase(),ms=n==='hourly'?3600000:n==='weekly'?604800000:n==='realtime'?900000:86400000;return new Date(Date.now()+ms).toISOString()}
async function claim(admin:any,s:Schedule){const until=new Date(Date.now()+900000).toISOString();let q=admin.from('rss_schedules').update({next_run_at:until,updated_at:new Date().toISOString()}).eq('id',s.id);q=s.next_run_at?q.eq('next_run_at',s.next_run_at):q.is('next_run_at',null);const{data,error}=await q.select('id').maybeSingle();if(error)throw error;return Boolean(data)}
async function call(url:string,key:string,slug:string,body:any){const r=await fetch(`${url}/functions/v1/${slug}`,{method:'POST',headers:{Authorization:`Bearer ${key}`,apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(120000)});const text=await r.text();let data:any={};try{data=JSON.parse(text)}catch{data={error:text.slice(0,800)}}return{ok:r.ok&&data?.success!==false,status:r.status,data}}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{headers:H});if(req.method!=='POST')return J({success:false,error:'Method not allowed'},405);const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return J({success:false,error:'Autorização necessária'},401);const token=auth.slice(7);if(jwtRole(token)!=='service_role')return J({success:false,error:'Execução restrita ao serviço de automação'},403);const url=Deno.env.get('SUPABASE_URL')||'',key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!key)return J({success:false,error:'Backend incompleto'},500);const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),now=new Date().toISOString();const{data:schedules,error}=await admin.from('rss_schedules').select('id,user_id,project_id,feed_url,feed_name,niche,article_length,frequency,auto_publish,last_run_at,next_run_at,articles_generated').eq('is_active',true).or(`next_run_at.is.null,next_run_at.lte.${now}`).order('next_run_at',{ascending:true,nullsFirst:true}).limit(25);if(error)return J({success:false,error:error.message},500);if(!schedules?.length)return J({success:true,processed:0,queued:0,schedules:[]});let processed=0,queued=0;const results:any[]=[];
for(const raw of schedules){const s=raw as Schedule;try{if(!(await claim(admin,s)))continue;const items=await fetchFeed(s.feed_url);let created=0,enqueued=0;await admin.from('monitored_portals').update({last_check_at:new Date().toISOString(),last_success_at:new Date().toISOString(),last_error:null,last_articles_found:items.length,updated_at:new Date().toISOString()}).eq('project_id',s.project_id).eq('rss_feed_url',s.feed_url);for(const item of items.slice(0,3)){const rewrite=await call(url,key,'rewrite-news',{sourceUrl:item.link,sourceContent:item.content||item.description||item.title,sourceName:s.feed_name,analysisAngle:'AUTO_SEMANTIC',niche:'auto',articleLength:'auto',projectId:s.project_id,userId:s.user_id,language:'pt-BR'});if(!rewrite.ok||!rewrite.data?.article){results.push({schedule_id:s.id,source_url:item.link,stage:'rewrite',error:String(rewrite.data?.error||`HTTP ${rewrite.status}`).slice(0,500)});continue}if(!rewrite.data.duplicate){created++;processed++}const article=rewrite.data.article;const currentConfig=article.config&&typeof article.config==='object'?article.config:{};await admin.from('articles').update({config:{...currentConfig,schedule_id:s.id,rss_published_at:item.publishedAt,rss_source_url:item.link,rss_feed_url:s.feed_url}}).eq('id',article.id);if(s.auto_publish&&s.project_id&&!rewrite.data.duplicate&&article.status==='ready'&&Number(article.originality_score||0)>=95){const pub=await call(url,key,'wordpress-operations',{action:'publish',articleId:article.id,projectId:s.project_id,userId:s.user_id,publishStatus:'publish'});if(pub.ok){enqueued++;queued++}else results.push({schedule_id:s.id,article_id:article.id,stage:'distribution',error:String(pub.data?.error||`HTTP ${pub.status}`).slice(0,500)})}}
await admin.from('rss_schedules').update({last_run_at:new Date().toISOString(),next_run_at:nextRun(s.frequency),articles_generated:Number(s.articles_generated||0)+created,updated_at:new Date().toISOString()}).eq('id',s.id);results.push({schedule_id:s.id,feed:s.feed_name,items_found:items.length,created,queued:enqueued,success:true})}catch(e){const message=e instanceof Error?e.message:'Erro desconhecido';await admin.from('rss_schedules').update({next_run_at:nextRun(s.frequency),updated_at:new Date().toISOString()}).eq('id',s.id);await admin.from('monitored_portals').update({last_check_at:new Date().toISOString(),last_error:message.slice(0,1000),updated_at:new Date().toISOString()}).eq('project_id',s.project_id).eq('rss_feed_url',s.feed_url);results.push({schedule_id:s.id,success:false,error:message})}}
return J({success:true,processed,queued,schedules:results})});
