<?php
if (!defined('ABSPATH')) exit;
final class Zica_Posts_Admin {
    private $auth; private $discovery; private $outbox; private $curator;
    public function __construct($auth,$discovery,$outbox,$curator){$this->auth=$auth;$this->discovery=$discovery;$this->outbox=$outbox;$this->curator=$curator;add_action('admin_menu',array($this,'menu'));add_action('admin_init',array($this,'settings'));add_action('admin_enqueue_scripts',array($this,'assets'));}
    public function menu(){add_menu_page('Zica Posts','Zica Posts','manage_options','zica-posts',array($this,'page'),'dashicons-networking',58);}
    public function settings(){foreach(array('zica_posts_ai_crawlers_enabled','zica_posts_physical_files_enabled','zica_posts_hub_enabled','zica_posts_hub_delegates_indexing','zica_posts_hub_delegates_discovery','zica_posts_auto_correction_enabled') as $key)register_setting('zica_posts_settings',$key,array('sanitize_callback'=>'sanitize_text_field'));register_setting('zica_posts_settings','zica_posts_cards_position',array('sanitize_callback'=>'sanitize_key'));register_setting('zica_posts_settings','zica_posts_cards_count',array('sanitize_callback'=>'absint'));register_setting('zica_posts_settings','zica_posts_hub_webhook_url',array('sanitize_callback'=>array($this,'sanitize_hub_url')));}
    public function sanitize_hub_url($value){$url=esc_url_raw((string)$value);return $url&&$this->auth->hub_url_is_safe($url)?$url:'';}
    public function assets($hook){if('toplevel_page_zica-posts'===$hook)wp_enqueue_style('zica-posts-admin',ZICA_POSTS_URL.'assets/admin.css',array(),ZICA_POSTS_VERSION);}
    private function action_form($post_id,$operation,$label,$class='secondary small'){$confirm='delete'===$operation?' onsubmit="return confirm(\'Excluir permanentemente este artigo? Esta ação não pode ser desfeita.\')"':'';echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" class="zica-inline"'.$confirm.'><input type="hidden" name="action" value="zica_posts_curator_action"><input type="hidden" name="post_id" value="'.esc_attr($post_id).'"><input type="hidden" name="operation" value="'.esc_attr($operation).'">';wp_nonce_field('zica_posts_curator_'.$operation.'_'.$post_id);submit_button($label,$class,'submit',false);echo '</form>';}
    public function page(){if(!current_user_can('manage_options'))return;$counts=$this->outbox->counts();echo '<div class="wrap zica-posts-admin"><div class="zica-posts-hero"><div class="zica-posts-kicker">ZICA.AI · CURADORIA EDITORIAL</div><h1>Zica Posts '.esc_html(ZICA_POSTS_VERSION).'</h1><p>Conector leve, outbox resiliente e auditoria pós-publicação com correções seguras, revisões e alertas de duplicidade.</p></div>';echo '<div class="zica-posts-grid"><section class="zica-posts-panel"><h2>Conexão segura</h2><p><strong>Namespace:</strong> <code>/wp-json/zica-posts/v1/</code></p><p>Credenciais protegidas nas opções do WordPress.</p></section><section class="zica-posts-panel"><h2>Outbox</h2><p>Pending: '.esc_html($counts['pending']??0).' · Retry: '.esc_html($counts['retry']??0).' · Failed: '.esc_html($counts['failed']??0).'</p></section></div>';echo '<form method="post" action="options.php" class="zica-posts-panel zica-posts-settings">';settings_fields('zica_posts_settings');echo '<h2>Autocorreção</h2><label><input type="checkbox" name="zica_posts_auto_correction_enabled" value="1" '.checked(get_option('zica_posts_auto_correction_enabled','1'),'1',false).'> Aparar automaticamente símbolos editoriais seguros ao salvar posts</label><p class="description">Duplicidades, mídia ausente e categoria padrão geram advertência. O plugin nunca exclui conteúdo automaticamente.</p>';submit_button('Salvar controles');echo '</form>';$this->render_findings();echo '</div>';}
    private function render_findings(){$posts=$this->curator->recent_findings();echo '<section class="zica-posts-panel"><h2>Auditoria e autocorreção</h2><table class="widefat striped"><thead><tr><th>Artigo</th><th>Status</th><th>Advertências</th><th>Ações</th></tr></thead><tbody>';if(!$posts)echo '<tr><td colspan="4">Nenhuma advertência registrada.</td></tr>';foreach($posts as $post){$warnings=get_post_meta($post->ID,Zica_Posts_Curator::META_WARNINGS,true);if(!$warnings)continue;echo '<tr><td><strong>'.esc_html($post->post_title).'</strong><br><small>#'.esc_html($post->ID).'</small></td><td>'.esc_html($post->post_status).'</td><td><ul>';foreach((array)$warnings as $warning)echo '<li>'.esc_html($warning['message']??'Advertência editorial').'</li>';echo '</ul></td><td class="zica-actions"><a class="button button-secondary button-small" href="'.esc_url(get_edit_post_link($post->ID)).'">Editar</a>';if('trash'!==$post->post_status){$this->action_form($post->ID,'correct','Corrigir seguro');$this->action_form($post->ID,'trash','Mover para lixeira');}else{$this->action_form($post->ID,'delete','Excluir permanentemente','delete small');}echo '</td></tr>';}echo '</tbody></table></section>';}
}
