<?php
if (!defined('ABSPATH')) exit;
final class Zica_Posts_Cards {
 public function __construct(){add_action('wp_enqueue_scripts',array($this,'enqueue_public_assets'));add_filter('the_content',array($this,'inject'),30);add_shortcode('zica_posts_cards',array($this,'shortcode'));}
 public function enqueue_public_assets(){if(is_singular('post'))wp_enqueue_style('zica-posts-cards',ZICA_POSTS_URL.'assets/frontend.css',array(),ZICA_POSTS_VERSION);}
 private function related($post_id,$count){$cats=wp_get_post_categories($post_id);$args=array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>max(1,min(6,absint($count))),'post__not_in'=>array($post_id),'orderby'=>'date','order'=>'DESC');if($cats)$args['category__in']=$cats;return get_posts($args);}
 public function render($post_id,$count){$posts=$this->related($post_id,$count);if(!$posts)return '';$html='<section class="zica-posts-related" aria-label="Conteúdos relacionados"><div class="zica-posts-related__head"><span>ZICA.AI</span><h2>Continue nesta onda</h2></div><div class="zica-posts-related__grid">';foreach($posts as $item){$html.='<article class="zica-posts-card"><a href="'.esc_url(get_permalink($item->ID)).'">';$thumb=get_the_post_thumbnail_url($item->ID,'medium_large');if($thumb)$html.='<img loading="lazy" decoding="async" src="'.esc_url($thumb).'" alt="'.esc_attr(wp_strip_all_tags($item->post_title)).'">';$html.='<div class="zica-posts-card__body"><h3>'.esc_html($item->post_title).'</h3><p>'.esc_html(wp_trim_words(wp_strip_all_tags($item->post_excerpt?:$item->post_content),18)).'</p><span>Continuar lendo →</span></div></a></article>';}$html.='</div></section>';return $html;}
 private function insert_after_paragraph($content,$insert,$n){$parts=explode('</p>',$content);if(count($parts)<=$n)return $content.$insert;$out='';foreach($parts as $i=>$part){if(''===trim($part)&&$i===count($parts)-1)continue;$out.=$part.'</p>';if(($i+1)===$n)$out.=$insert;}return $out;}
 private function editorial_wrap($content){if(false!==strpos($content,'class="zica-editorial-content"'))return $content;return '<div class="zica-editorial-content" data-editorial-version="2">'.$content.'</div>';}
 public function inject($content){if(is_admin()||!is_singular('post')||!in_the_loop()||!is_main_query())return $content;global $post;if(!$post instanceof WP_Post)return $content;$position=get_option('zica_posts_cards_position','after_content');$cards='disabled'===$position?'':$this->render($post->ID,get_option('zica_posts_cards_count',3));if(!$cards)return $this->editorial_wrap($content);if('before_content'===$position)return $cards.$this->editorial_wrap($content);if('after_p2'===$position)return $this->editorial_wrap($this->insert_after_paragraph($content,$cards,2));if('after_p4'===$position)return $this->editorial_wrap($this->insert_after_paragraph($content,$cards,4));return $this->editorial_wrap($content).$cards;}
 public function shortcode($atts){$atts=shortcode_atts(array('count'=>get_option('zica_posts_cards_count',3)),$atts,'zica_posts_cards');$id=get_the_ID();return $id?$this->render($id,absint($atts['count'])):'';}
 public function settings(){return array('position'=>get_option('zica_posts_cards_position','after_content'),'count'=>(int)get_option('zica_posts_cards_count',3));}
}