<?php
if (!defined('ABSPATH')) exit;
// Agente.IA Auditor: checagens de leitura (robots.txt, arquivos de discovery, schema por
// artigo, schema de homepage, hreflang) acionáveis pelo plugin (admin-post) e via REST (GET /ai-audit).
final class Zica_Posts_AI_Auditor {
 private $discovery;
 public function __construct($discovery){$this->discovery=$discovery;}
 public function run_audit(){$checks=array($this->check_robots(),$this->check_discovery_files(),$this->check_article_schema(),$this->check_homepage_schema(),$this->check_hreflang());return array('score'=>$this->score_from_checks($checks),'checks'=>$checks,'generated_at'=>(new DateTimeImmutable('now',new DateTimeZone(ZICA_POSTS_TZ)))->format(DateTime::ATOM));}
 private function score_from_checks($checks){$weights=array('pass'=>1,'info'=>0.85,'warn'=>0.5,'fail'=>0);$max=count($checks)?:1;$total=0;foreach($checks as $c)$total+=isset($weights[$c['status']])?$weights[$c['status']]:0.5;return (int) round(100*$total/$max);}
 private function bot_blocked($bot,$content){return (bool) preg_match('/User-agent:\s*'.preg_quote($bot,'/').'\s*\n(?:.*\n)*?\s*Disallow:\s*\/\s*$/im',$content);}
 private function check_robots(){$response=wp_remote_get(home_url('/robots.txt'),array('timeout'=>10));if(is_wp_error($response))return array('id'=>'robots_txt','label'=>'robots.txt permite bots de IA','status'=>'warn','detail'=>'Não foi possível buscar robots.txt: '.$response->get_error_message());$content=(string) wp_remote_retrieve_body($response);$bots=$this->discovery->ai_bots();$blocked=array();foreach($bots as $bot)if($this->bot_blocked($bot,$content))$blocked[]=$bot;$ok=count($bots)-count($blocked);$status=$blocked?($ok>0?'warn':'fail'):'pass';$detail=$ok.'/'.count($bots).' bots de IA liberados no robots.txt.'.($blocked?' Bloqueados: '.implode(', ',$blocked).'.':'');return array('id'=>'robots_txt','label'=>'robots.txt permite bots de IA','status'=>$status,'detail'=>$detail);}
 private function check_discovery_files(){$status=get_option('zica_posts_discovery_files_status',array());$expected=array('llms.txt','llms-full.txt','ai.txt','zica-ai-manifest.json','zica-ai-sitemap.xml');$missing=array();foreach($expected as $name)if(!isset($status[$name]))$missing[]=$name;$physical='1'===(string) get_option('zica_posts_physical_files_enabled','1');$age_h=null;$stale=(bool) $missing;if($physical&&!$missing){$newest=0;foreach($expected as $name){$path=ABSPATH.$name;if(file_exists($path))$newest=max($newest,filemtime($path));}if($newest){$age_h=round((time()-$newest)/3600,1);$stale=$age_h>24;}else{$stale=true;}}if($missing||$stale){if(method_exists($this->discovery,'schedule_refresh'))$this->discovery->schedule_refresh(0);$level=$missing?'fail':'warn';$detail=$missing?('Arquivos ausentes: '.implode(', ',$missing).'.'):('Arquivos desatualizados há '.$age_h.'h; atualização agendada.');}else{$level='pass';$detail=$physical?('Arquivos atualizados há '.$age_h.'h.'):'Modo de arquivo virtual ativo (conteúdo sempre atual na entrega).';}return array('id'=>'discovery_files','label'=>'llms.txt / llms-full.txt / ai.txt / manifest / sitemap','status'=>$level,'detail'=>$detail);}
 private function check_article_schema(){$q=new WP_Query(array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>20,'orderby'=>'modified','order'=>'DESC','fields'=>'ids','no_found_rows'=>true));$ids=$q->posts;$total=count($ids);if(!$total)return array('id'=>'article_schema','label'=>'Schema JSON-LD nos artigos','status'=>'info','detail'=>'Nenhum artigo publicado para avaliar.');$with=0;foreach($ids as $id){$schema=get_post_meta($id,'_zica_posts_json_ld',true);if(is_array($schema)&&$schema)$with++;}$ratio=$with/$total;$status=$ratio>=0.9?'pass':($ratio>0?'warn':'fail');return array('id'=>'article_schema','label'=>'Schema JSON-LD nos artigos','status'=>$status,'detail'=>$with.'/'.$total.' dos últimos artigos publicados têm schema estruturado (_zica_posts_json_ld).');}
 private function check_homepage_schema(){$schema=get_option('zica_posts_homepage_schema',array());$has=is_array($schema)&&$schema;return array('id'=>'homepage_schema','label'=>'Schema JSON-LD da homepage','status'=>$has?'pass':'warn','detail'=>$has?('Homepage possui '.count($schema).' schema(s) estruturado(s).'):'Nenhum schema de homepage configurado (Organization/LegalService).');}
 private function check_hreflang(){global $wpdb;$count=(int) $wpdb->get_var($wpdb->prepare("SELECT COUNT(DISTINCT post_id) FROM {$wpdb->postmeta} WHERE meta_key=%s AND meta_value<>'' AND meta_value<>'a:0:{}'",'_zica_posts_hreflang_map'));if(!$count)return array('id'=>'hreflang','label'=>'hreflang entre traduções','status'=>'info','detail'=>'Nenhum artigo com mapa de hreflang configurado — normal em site de idioma único.');return array('id'=>'hreflang','label'=>'hreflang entre traduções','status'=>'pass','detail'=>$count.' artigo(s) com mapa de hreflang configurado.');}
}
