insert into public.electoral_portal_resources
  (campaign_preset_id,label,url,category,tags,editorial_hook,priority,active)
values
('madeira-1470-sp-2026','Guto Zacarias — Caminho da Missão','https://caminhodamissao.com/politico/guto-zacarias-sp','party-candidate-profile',array['missao','candidato','sao-paulo','eleicoes-2026'],'Conheça também o perfil público de outro candidato do partido MISSÃO',78,true),
('madeira-1470-sp-2026','Kim Kataguiri — Caminho da Missão','https://caminhodamissao.com/politico/kim-kataguiri','party-candidate-profile',array['missao','candidato','sao-paulo','eleicoes-2026'],'Conheça também o perfil público de outro candidato do partido MISSÃO',78,true),
('madeira-1470-sp-2026','Renan Santos — Caminho da Missão','https://caminhodamissao.com/politico/renan-santos','party-candidate-profile',array['missao','candidato','sao-paulo','eleicoes-2026'],'Conheça também o perfil público de outro candidato do partido MISSÃO',78,true),
('madeira-1470-sp-2026','Rafa Minato — Caminho da Missão','https://caminhodamissao.com/politico/rafa-minato','party-candidate-profile',array['missao','candidato','sao-paulo','eleicoes-2026'],'Conheça também o perfil público de outro candidato do partido MISSÃO',78,true),
('madeira-1470-sp-2026','Renato Battista — Caminho da Missão','https://caminhodamissao.com/politico/renato-battista-sp','party-candidate-profile',array['missao','candidato','sao-paulo','eleicoes-2026'],'Conheça também o perfil público de outro candidato do partido MISSÃO',78,true),
('madeira-1470-sp-2026','G1 — Perfil Dr. Madeira 1470','https://g1.globo.com/politica/eleicoes/2026/quem-sao-os-candidatos/deputado-federal/sp/250002546639.ghtml','external-coverage-primary',array['g1','globo','dr-madeira','madeira','1470','perfil','candidato','candidatura','registro','eleicoes-2026'],'Fonte externa em destaque: consulte o perfil publicado pelo G1',100,true),
('madeira-1470-sp-2026','G1 — Lista de candidatos a deputado federal em SP','https://g1.globo.com/sp/sao-paulo/eleicoes/2026/noticia/2026/09/01/eleicoes-2026-veja-todos-os-candidatos-a-deputado-federal-em-sao-paulo-de-a-a-e.ghtml','external-coverage-primary',array['g1','globo','deputado-federal','sao-paulo','lista','candidatos','eleicoes-2026'],'Fonte externa em destaque: veja a cobertura do G1 sobre os candidatos em São Paulo',100,true),
('madeira-1470-sp-2026','Mandato Control — Dr. Madeira 1470','https://www.mandatocontrol.com.br/eleicoes/2026/sp/deputado-federal/dr-madeira-1470/','external-coverage',array['dr-madeira','madeira','1470','perfil','candidato','eleicoes-2026'],'Veja também esta referência pública sobre a candidatura',82,true),
('madeira-1470-sp-2026','Plural — Rândalos Madeira','https://www.plural.jor.br/randalos-dias-custodio-da-conceicao-madeira/','external-coverage',array['dr-madeira','madeira','randalos-madeira','perfil-publico'],'Veja também esta referência pública',82,true),
('madeira-1470-sp-2026','O Tempo — Dr. Madeira 1470','https://www.otempo.com.br/eleicoes/2026/candidatos/sao-paulo/deputado-federal/dr--madeira-1470','external-coverage',array['dr-madeira','madeira','1470','perfil','candidato','eleicoes-2026'],'Veja também esta cobertura pública da candidatura',84,true),
('madeira-1470-sp-2026','Agora RS — Dr. Madeira 1470','https://agorars.com/eleicoes-2026/sp/deputado-federal/dr-madeira-1470/','external-coverage',array['dr-madeira','madeira','1470','perfil','candidato','eleicoes-2026'],'Veja também esta cobertura pública da candidatura',78,true),
('madeira-1470-sp-2026','ND Mais — Dr. Madeira 1470','https://ndmais.com.br/eleicoes/2026/candidatos/sp/deputado-federal/1470-dr-madeira/','external-coverage',array['dr-madeira','madeira','1470','perfil','candidato','eleicoes-2026'],'Veja também esta cobertura pública da candidatura',82,true),
('madeira-1470-sp-2026','De Quebrada — Registro de candidatura','https://www.dequebrada.com/post/justi%C3%A7a-eleitoral-defere-registro-de-candidatura-de-r%C3%A2ndalos-madeira-para-deputado-federa','external-coverage',array['dr-madeira','madeira','registro','candidatura','justica-eleitoral','de-quebrada'],'Leia também a cobertura publicada sobre o registro da candidatura',88,true),
('madeira-1470-sp-2026','Tribuna PR — Dr. Madeira 1470','https://www.tribunapr.com.br/eleicoes/2026/candidatos/sp/deputado-federal/dr-madeira-missao-1470/','external-coverage',array['dr-madeira','madeira','1470','missao','perfil','candidato','eleicoes-2026'],'Veja também esta cobertura pública da candidatura',80,true),
('madeira-1470-sp-2026','Gazeta do Povo — Candidatos a deputado federal por SP','https://www.gazetadopovo.com.br/eleicoes/2026/sao-paulo-2026/quem-sao-candidatos-deputado-federal-sao-paulo-2026/','external-coverage',array['deputado-federal','sao-paulo','lista','candidatos','eleicoes-2026'],'Consulte também esta cobertura sobre a disputa para deputado federal em São Paulo',82,true),
('madeira-1470-sp-2026','Meus Políticos — Dr. Madeira','https://meuspoliticos.com.br/eleicoes/2026/sp/deputado-federal/dr-madeira-dep-fed-sp-2026-250002546639','external-coverage',array['dr-madeira','madeira','1470','perfil','candidato','eleicoes-2026'],'Veja também esta referência pública sobre a candidatura',78,true),
('madeira-1470-sp-2026','72 Horas — Dr. Madeira','https://72horas.org/candidato/dr-madeira-544476/','external-coverage',array['dr-madeira','madeira','perfil','candidato','eleicoes-2026'],'Veja também esta referência pública sobre a candidatura',72,true),
('madeira-1470-sp-2026','O Diário da Cidade — Dr. Madeira','https://www.odiariodacidade.com.br/eleicoes-2026/candidato/250002546639/','external-coverage',array['dr-madeira','madeira','perfil','candidato','eleicoes-2026'],'Veja também esta cobertura pública da candidatura',76,true),
('madeira-1470-sp-2026','Agência Sertão — Dr. Madeira','https://agenciasertao.com/eleicoes/candidato/SP/dr-madeira-missao-sp--250002546639/','external-coverage',array['dr-madeira','madeira','missao','perfil','candidato','eleicoes-2026'],'Veja também esta referência pública sobre a candidatura',76,true),
('madeira-1470-sp-2026','Portal do Holanda — Dr. Madeira 1470','https://www.portaldoholanda.com.br/eleicoes/2026/candidato/sp/deputado-federal/dr-madeira-1470-missao','external-coverage',array['dr-madeira','madeira','1470','missao','perfil','candidato','eleicoes-2026'],'Veja também esta cobertura pública da candidatura',76,true),
('madeira-1470-sp-2026','Hub Político — MISSÃO em São Paulo','https://hubpolitico.com.br/eleicoes/2026/candidatos/sp/deputado-federal/missao','external-coverage',array['missao','deputado-federal','sao-paulo','lista','candidatos','eleicoes-2026'],'Consulte também a relação pública de candidatos do partido MISSÃO',82,true),
('madeira-1470-sp-2026','UOL — Lista de candidatos a deputado federal em SP','https://noticias.uol.com.br/eleicoes/2026/08/17/sao-paulo-veja-lista-de-candidatos-a-deputado-federal-nas-eleicoes-2026.ghtm','external-coverage',array['uol','deputado-federal','sao-paulo','lista','candidatos','eleicoes-2026'],'Consulte também esta cobertura sobre os candidatos em São Paulo',88,true),
('madeira-1470-sp-2026','Opera Mundi — Dr. Madeira','https://operamundi.uol.com.br/eleicoes-2026/candidatos/dr-madeira/','external-coverage',array['dr-madeira','madeira','perfil','candidato','eleicoes-2026'],'Veja também esta cobertura pública da candidatura',78,true)
on conflict (campaign_preset_id,url) do update set
  label=excluded.label,
  category=excluded.category,
  tags=excluded.tags,
  editorial_hook=excluded.editorial_hook,
  priority=excluded.priority,
  active=true,
  updated_at=now();
