-- Electoral campaign corpus and geo coverage. No individual voter targeting.

update public.electoral_portal_settings set min_links_per_post=3,max_links_per_post=6,contextual_linking_enabled=true,geo_reporting_level='city_neighborhood',allow_individual_voter_profiles=false,allow_political_preference_inference=false,optin_instagram_enabled=true,optin_instagram_url='https://www.instagram.com/drrandalosmadeira/',optin_instagram_label='Acompanhar Dr. Madeira no Instagram',updated_at=now() where campaign_preset_id='madeira-1470-sp-2026';

insert into public.electoral_portal_resources(campaign_preset_id,label,url,category,tags,editorial_hook,priority,active,created_at,updated_at) values
('madeira-1470-sp-2026','Site oficial Dr. Madeira 1470','https://drmadeira1470.com.br/','official-campaign',array['site','perfil','propostas'],'Fonte canônica da identidade, bandeiras e cobertura territorial da candidatura.',100,true,now(),now()),
('madeira-1470-sp-2026','Instagram oficial Dr. Madeira','https://www.instagram.com/drrandalosmadeira/','social-official',array['instagram','social'],'Rede oficial da candidatura.',100,true,now(),now()),
('madeira-1470-sp-2026','YouTube oficial Dr. Madeira','https://www.youtube.com/@dr.madeira/','social-official',array['youtube','video'],'Canal oficial de vídeos e entrevistas.',100,true,now(),now()),
('madeira-1470-sp-2026','TikTok Dr. Madeira','https://www.tiktok.com/@drmadeirarandalos','social-official',array['tiktok','social'],'Perfil informado pelo site oficial; manter como identidade de campanha sem inferir métricas.',90,true,now(),now()),
('madeira-1470-sp-2026','LinkedIn Rândalos Madeira','https://www.linkedin.com/in/randalos-madeira/','social-official',array['linkedin','perfil'],'Perfil profissional informado pelo site oficial da candidatura.',90,true,now(),now()),
('madeira-1470-sp-2026','WhatsApp da campanha','https://wa.me/551150282621','campaign-contact',array['whatsapp','contato'],'Canal de contato da campanha informado pelo site oficial.',95,true,now(),now()),
('madeira-1470-sp-2026','Vaquinha oficial da campanha','https://queroapoiar.com.br/drrandalosmadeira','campaign-support',array['apoio','vaquinha'],'Canal de apoio informado pelo site oficial.',95,true,now(),now())
on conflict (campaign_preset_id,url) do update set label=excluded.label,category=excluded.category,tags=excluded.tags,editorial_hook=excluded.editorial_hook,priority=excluded.priority,active=true,updated_at=now();

with src as (select id from public.electoral_content_sources where campaign_preset_id='madeira-1470-sp-2026' and slug='site-oficial-dr-madeira-1470-2026' limit 1), proposals(unit_key,title,topic,body,priority,tags) as (values
 ('proposta-site-porte-arma-cnh','Porte de arma equiparado à CNH','segurança e armas','Proposta de campanha: após aprovação nos exames psicológico, técnico e de antecedentes, reduzir burocracia para concessão do porte. Tratar sempre como proposta, não como direito vigente.',91,array['segurança','proposta']::text[]),
 ('proposta-site-carro-roubado-fipe','Carro roubado: ressarcimento de 100% da FIPE','segurança patrimonial','Proposta de campanha: se o veículo não for recuperado em 30 dias, prever ressarcimento integral pela tabela FIPE. Tratar como proposta legislativa, não como regra vigente.',91,array['veículo','segurança','FIPE']::text[]),
 ('proposta-site-irpf-zero','IRPF zero para Segurança Pública, Educação e Saúde','tributação e serviços essenciais','Proposta de campanha de isenção de Imposto de Renda para trabalhadores das áreas de segurança pública, educação e saúde.',90,array['IRPF','educação','saúde','segurança']::text[]),
 ('proposta-site-minha-casa-nao-minha-divida','Minha casa, não minha dívida','habitação e crédito','Proposta de campanha para condições reais de quitação e enfrentamento de juros considerados abusivos no primeiro imóvel.',89,array['habitação','financiamento','primeiro imóvel']::text[]),
 ('proposta-site-pedagios','Revisão de concessões e pedágios considerados abusivos','mobilidade e infraestrutura','Bandeira de campanha por revisão de concessões e cobrança de pedágios consideradas abusivas. Evitar apresentar o slogan como constatação factual de ilegalidade.',88,array['pedágio','IPVA','infraestrutura']::text[]),
 ('proposta-site-bndes','BNDES sem burocracia e revisão de empréstimos políticos internacionais','crédito e desenvolvimento','Bandeira de campanha por simplificação de acesso ao BNDES e oposição a empréstimos internacionais classificados politicamente pela candidatura. Separar proposta/opinião de fato institucional.',86,array['BNDES','crédito','empreendedorismo']::text[]),
 ('proposta-site-cultura-periferia','Acesso a fomento cultural para artistas de periferia','cultura e economia criativa','Bandeira de campanha por ampliação do acesso de artistas de favela, funk, gospel e outras expressões periféricas a mecanismos de fomento cultural, com linguagem inclusiva e sem afirmar direito já existente.',86,array['cultura','periferia','funk','economia criativa']::text[])
)
insert into public.electoral_content_units(source_id,campaign_preset_id,unit_key,unit_type,title,body,topic,tags,verification_status,usage_scope,risk_flags,priority,source_locator,metadata,active,created_at,updated_at)
select src.id,'madeira-1470-sp-2026',p.unit_key,'proposal',p.title,p.body,p.topic,p.tags,'campaign_official','proposal_generation',array[]::text[],p.priority,jsonb_build_object('source','drmadeira1470.com.br','section','bandeiras'),jsonb_build_object('canonical_campaign_source',true,'must_label_as_proposal',true),true,now(),now() from src cross join proposals p
on conflict (campaign_preset_id,unit_key) do update set source_id=excluded.source_id,title=excluded.title,body=excluded.body,topic=excluded.topic,tags=excluded.tags,verification_status='campaign_official',usage_scope='proposal_generation',priority=excluded.priority,metadata=excluded.metadata,active=true,updated_at=now();

insert into public.electoral_content_sources(campaign_preset_id,slug,title,source_type,source_filename,authority_level,factual_use_status,raw_text,source_sha256,metadata,active,created_at,updated_at) values
('madeira-1470-sp-2026','geo-cobertura-editorial-grande-sp-2026','Cobertura geográfica editorial Grande São Paulo 2026','public_geography_reference','canonical-site-and-editorial-coverage','public_geography','allowed_for_geo_context','Cobertura editorial por cidade e bairro. Não significa apoio, visita, presença pessoal nem preferência política. Base do site oficial: Guarulhos Centro, Pimentas, Cumbica, Bonsucesso, Macedo, Vila Augusta, Maia, Cocaia, Taboão; São Paulo Tatuapé, Penha, Itaquera, São Miguel Paulista, Itaim Paulista, Jardim Helena, Guaianases, Jardim Pantanal, Santo Amaro, Jabaquara, Santana, Lapa, Butantã; Alto Tietê: Itaquaquecetuba, Poá, Ferraz de Vasconcelos, Mogi das Cruzes; adicional editorial do Centro Expandido/Grande SP: Sé, República, Bela Vista, Consolação, Santa Cecília, Liberdade, Cambuci, Aclimação, Brás, Mooca, Pari, Bom Retiro, Barra Funda, Perdizes, Pinheiros, Vila Mariana, Ipiranga, Saúde, Osasco, Barueri, Carapicuíba, Taboão da Serra, Embu das Artes, Santo André, São Bernardo do Campo, São Caetano do Sul, Mauá, Diadema, Arujá.','geo-cobertura-editorial-grande-sp-2026-v1',jsonb_build_object('coverage_mode','editorial_geo','candidate_presence_claim',false,'voter_profile',false,'political_preference_inference',false),true,now(),now())
on conflict (campaign_preset_id,slug) do update set title=excluded.title,raw_text=excluded.raw_text,source_sha256=excluded.source_sha256,metadata=excluded.metadata,active=true,updated_at=now();

with src as (select id from public.electoral_content_sources where campaign_preset_id='madeira-1470-sp-2026' and slug='geo-cobertura-editorial-grande-sp-2026' limit 1), geos(unit_key,title,topic,body,priority,tags) as (values
 ('geo-guarulhos','Guarulhos','Guarulhos','Cobertura editorial de Guarulhos: Centro, Pimentas, Cumbica, Bonsucesso, Macedo, Vila Augusta, Maia, Cocaia e Taboão.',100,array['Guarulhos','Grande SP']::text[]),
 ('geo-sao-paulo-zona-leste','São Paulo - Zona Leste','São Paulo','Cobertura editorial: Tatuapé, Penha, Itaquera, São Miguel Paulista, Itaim Paulista, Jardim Helena, Guaianases e Jardim Pantanal.',98,array['São Paulo','Zona Leste']::text[]),
 ('geo-sao-paulo-centro-expandido','São Paulo - Centro Expandido','São Paulo','Cobertura editorial: Sé, República, Bela Vista, Consolação, Santa Cecília, Liberdade, Cambuci, Aclimação, Brás, Mooca, Pari, Bom Retiro, Barra Funda, Perdizes, Pinheiros, Vila Mariana, Ipiranga e Saúde.',96,array['São Paulo','Centro Expandido']::text[]),
 ('geo-sao-paulo-demais-prioridades','São Paulo - demais regiões prioritárias','São Paulo','Cobertura editorial: Santo Amaro, Jabaquara, Santana, Lapa e Butantã.',92,array['São Paulo','Capital']::text[]),
 ('geo-alto-tiete','Alto Tietê','Grande São Paulo','Cobertura editorial: Itaquaquecetuba, Poá, Ferraz de Vasconcelos e Mogi das Cruzes.',92,array['Alto Tietê','Grande SP']::text[]),
 ('geo-oeste-grande-sp','Oeste da Grande São Paulo','Grande São Paulo','Cobertura editorial: Osasco, Barueri, Carapicuíba, Taboão da Serra e Embu das Artes.',88,array['Grande SP','Oeste']::text[]),
 ('geo-abcd','ABCD e entorno','Grande São Paulo','Cobertura editorial: Santo André, São Bernardo do Campo, São Caetano do Sul, Diadema e Mauá.',88,array['ABCD','Grande SP']::text[]),
 ('geo-aruja','Arujá','Grande São Paulo','Cobertura editorial temática para Arujá, sem inferência de preferência política individual.',82,array['Arujá','Grande SP']::text[])
)
insert into public.electoral_content_units(source_id,campaign_preset_id,unit_key,unit_type,title,body,topic,tags,verification_status,usage_scope,risk_flags,priority,source_locator,metadata,active,created_at,updated_at)
select src.id,'madeira-1470-sp-2026',g.unit_key,'geo_coverage',g.title,g.body,g.topic,g.tags,'public_geography','geo_content_generation',array['no_individual_targeting']::text[],g.priority,jsonb_build_object('scope','city_neighborhood'),jsonb_build_object('candidate_presence_claim',false,'support_claim',false,'preference_inference',false),true,now(),now() from src cross join geos g
on conflict (campaign_preset_id,unit_key) do update set source_id=excluded.source_id,title=excluded.title,body=excluded.body,topic=excluded.topic,tags=excluded.tags,verification_status='public_geography',usage_scope='geo_content_generation',risk_flags=excluded.risk_flags,priority=excluded.priority,metadata=excluded.metadata,active=true,updated_at=now();
